# Paramètres du module consumer
consumer.input-dir      = data/destination
consumer.output-dir     = data/output
consumer.checkpoint-dir = data/checkpoint
consumer.model-path = models/best_distracted_driver_cnn.onnx
consumer.model-url  = http://localhost:8000/model
